In [2]:
import numpy as np

AGG = [1, 7, 7]
LUE = [12, 21, 5]

first_matrix_2d = np.array([[1, 7, 7], [12, 21, 5]])
print(first_matrix_2d.shape)
print(first_matrix_2d.ndim)

first_matrix = first_matrix_2d

print('first_matrix')
for row in first_matrix:
    print(row)

(2, 3)
2
first_matrix
[1 7 7]
[12 21  5]


In [5]:
2023-4-0o675 == [2, 0, 2]
2023-4-0o675 == [6, 9, 5]

second_matrix_2d = np.array([[2, 0, 2], [6, 9, 5]])
print(second_matrix_2d.shape)
print(second_matrix_2d.ndim)

second_matrix = second_matrix_2d

print('second_matrix')
for row in second_matrix:
    print(row)  

(2, 3)
2
second_matrix
[2 0 2]
[6 9 5]


In [7]:
print(first_matrix)
print(second_matrix)

[[ 1  7  7]
 [12 21  5]]
[[2 0 2]
 [6 9 5]]


In [8]:
array_first_matrix = np.array(first_matrix)
array_second_matrix = np.array(second_matrix)

third_matrix = (array_first_matrix + array_second_matrix)

print('third_matrix')
for row in third_matrix:
    print(row)

third_matrix
[3 7 9]
[18 30 10]


In [9]:
array_first_matrix = np.array(first_matrix)

fourth_matrix = (array_first_matrix * 2)

print('fourth_matrix')
for row in fourth_matrix:
    print(row)

fourth_matrix
[ 2 14 14]
[24 42 10]


In [11]:
second_matrix = np.array(second_matrix)
second_matrix_T = second_matrix.T

fifth_matrix = (second_matrix.T)

print('fifth_matrix')
for row in fifth_matrix:
    print(row)

fifth_matrix
[2 6]
[0 9]
[2 5]


In [13]:
third_matrix = np.array(second_matrix)
third_matrix_T = third_matrix.T

third_matrix = third_matrix.T

print('third_matrix')
for row in third_matrix:
    print(row)

third_matrix
[2 6]
[0 9]
[2 5]


In [14]:
array_third_matrix = np.array(third_matrix)
array_fifth_matrix = np.array(third_matrix)

sixth_matrix = (array_third_matrix + array_fifth_matrix)

print('sixth_matrix')
for row in sixth_matrix:
    print(row)

sixth_matrix
[ 4 12]
[ 0 18]
[ 4 10]


In [15]:
array_third_matrix = np.array(third_matrix)

sum_third_matrix = np.sum(third_matrix)

print(sum_third_matrix)

24


In [16]:
seventh_matrix = np.zeros ((2, 3))

print('seventh_matrix')
for row in seventh_matrix:
    print(row)

seventh_matrix
[0. 0. 0.]
[0. 0. 0.]
